server:
  port: 26337
  ssl:
    enabled: true
    key-store: classpath:a2a-server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12

spring:
  main:
    banner-mode: off

a2at:
  server:
    agent-card: classpath:agentcard/transport_workbench_agent.json
    path-prefix: /a2a/json

a2a:
  orch-url: https://127.0.0.1:5001
  ssl-verify: false
