/*
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 *    License for the specific language governing permissions and limitations
 *    under the License.
 */

package com.openan.a2at.engine.client;

import com.openan.a2at.engine.control.EventCallback;
import com.openan.a2at.engine.control.ControlPoint;
import com.openan.a2at.engine.model.SendMessageResult;
import org.a2aproject.sdk.spec.AgentCard;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Communication client for sending A2A messages to remote agents.
 *
 * <p>Two message types:
 * <ul>
 *   <li>{@link #sendMessage} - SSE streaming, used during workflow execution
 *       (from {@link ControlPoint#onTask}). Goes through Task-T prompt generation,
 *       Negotiation-T auto-loop, and the global {@link EventCallback}.</li>
 *   <li>{@link #sendExtensionMessage} - one-shot, used for pre-positioning
 *       Authorization-T and Notification-T before the workflow starts.
 *       Bypasses Task-T and Negotiation-T. Does not use the global
 *       EventCallback; the {@link CompletableFuture} is the callback.</li>
 * </ul>
 */
public interface WorkflowEngineClient {

    /**
     * Send a message to an agent via SSE streaming. Used during workflow
     * execution. The engine handles Task-T prompt generation, Negotiation-T
     * auto-loop, auth, and extension header injection automatically.
     *
     * @param agentName  target agent name (must match AgentCard.name)
     * @param message    full assembled message text
     * @param contextId  optional context ID (null = auto-generated)
     * @param metadata   optional preset metadata
     * @return future completing with response text, task, metadata, task state
     */
    CompletableFuture<SendMessageResult> sendMessage(
            String agentName, String message, String contextId, Map<String, Object> metadata);

    /** Convenience: no context ID, no preset metadata. */
    default CompletableFuture<SendMessageResult> sendMessage(String agentName, String message) {
        return sendMessage(agentName, message, null, null);
    }

    /**
     * Send a one-shot extension message for pre-positioning (e.g.
     * Authorization-T whitelist, Notification-T subscription). Bypasses
     * Task-T prompt generation and Negotiation-T auto-loop.
     *
     * <p>The metadata value is generated by the A2A-T SDK (LLM + prompt
     * template). If the SDK cannot generate, the natural-language input
     * is used as-is.
     *
     * <p>Unlike {@link #sendMessage}, this method does not emit events
     * through the global {@link EventCallback}. The returned
     * {@link CompletableFuture} is the callback.
     *
     * @param agentName             target agent name
     * @param instruction           short instruction text (becomes parts)
     * @param naturalLanguageInput  input for SDK prompt generation
     * @param extension             extension type (never hardcode URIs)
     */
    CompletableFuture<SendMessageResult> sendExtensionMessage(
            String agentName, String instruction,
            String naturalLanguageInput, A2ATExtension extension);

    /** Convenience for Authorization-T pre-positioning. */
    default CompletableFuture<SendMessageResult> sendAuthorization(
            String agentName, String instruction, String naturalLanguageInput) {
        return sendExtensionMessage(agentName, instruction,
                naturalLanguageInput, A2ATExtension.AUTHORIZATION_T);
    }

    /** Convenience for Notification-T pre-positioning. */
    default CompletableFuture<SendMessageResult> sendNotification(
            String agentName, String instruction, String naturalLanguageInput) {
        return sendExtensionMessage(agentName, instruction,
                naturalLanguageInput, A2ATExtension.NOTIFICATION_T);
    }

    void setControlPoint(ControlPoint controlPoint);
    void setExtensionCallback(com.openan.a2at.engine.control.ExtensionCallback extensionCallback);
    void setEventCallback(EventCallback callback);
    void close();
    java.util.List<String> getAgentNames();

    /** Update the agent card map (e.g. after fetching new cards). */
    default void updateAgentCards(java.util.List<AgentCard> agentCards) {
        // Default no-op; implementations override
    }

    /** Register a custom extension handler. */
    default void registerHandler(ExtensionHandler handler) {
        // Default no-op; implementations override
    }
}
